version: "3"

services:
  mysql:
    container_name: todo_mysql
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
     - ./db/init.d:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  back:
    container_name: todo_back
    build:
      context: ./api
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app/
    env_file:
      - .env
    depends_on:
      - mysql

volumes:
  db-data:
    driver: local